app.start.mode: test

spring:
  application:
    name: Accounts
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS USERS\;CREATE SCHEMA IF NOT EXISTS CONTRACTS\;CREATE SCHEMA IF NOT EXISTS RECOM
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
      console:
        enabled: true
        path: /h2-console

server:
  port: 8083

supplier:
  search:
    radius: 10