app.start.mode: ${APP_START_MODE:dev}

spring:
  application:
    name: Accounts
  datasource:
    url: ${DB_HOST:}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
server:
  port: 8083
