spring:
  application:
    name: Accounts
  datasource:
    url: ${DB_HOST:}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: 8083

supplier:
  search:
    radius: ${SEARCH_RADIUS:49}
